# Generated by Django 6.0.8 on 2026-10-02 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'API client',
            },
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.CharField(help_text='Device serial, e.g. 588C819FAF3E', max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('amonia', 'Amonia Sensor'), ('soap', 'Liquid Soap Sensor'), ('tissue', 'Tissue Paper Sensor'), ('toilet_paper', 'Toilet Paper Sensor'), ('trash', 'Trash Level Sensor')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_battery', models.IntegerField(blank=True, null=True)),
                ('last_level', models.FloatField(blank=True, null=True)),
                ('last_condition', models.CharField(blank=True, max_length=50)),
                ('last_severity', models.CharField(blank=True, choices=[('normal', 'Normal (green)'), ('warning', 'Warning (orange)'), ('critical', 'Critical (red)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sensor device',
            },
        ),
        migrations.CreateModel(
            name='StatusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('amonia', 'Amonia Sensor'), ('soap', 'Liquid Soap Sensor'), ('tissue', 'Tissue Paper Sensor'), ('toilet_paper', 'Toilet Paper Sensor'), ('trash', 'Trash Level Sensor')], max_length=20)),
                ('condition', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('normal', 'Normal (green)'), ('warning', 'Warning (orange)'), ('critical', 'Critical (red)')], max_length=10)),
                ('min_level', models.FloatField(blank=True, help_text='Inclusive. Empty = no lower bound.', null=True)),
                ('max_level', models.FloatField(blank=True, help_text='Exclusive. Empty = no upper bound.', null=True)),
            ],
            options={
                'ordering': ('sensor_type', 'min_level'),
            },
        ),
        migrations.CreateModel(
            name='WashroomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_after_minutes', models.PositiveIntegerField(default=30, help_text='A device with no reading for longer than this is shown as Offline.')),
            ],
            options={
                'verbose_name': 'washroom config',
            },
        ),
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Feedback device serial', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washroom.apiclient')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('battery', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('normal', 'Normal (green)'), ('warning', 'Warning (orange)'), ('critical', 'Critical (red)')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washroom.apiclient')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='washroom.sensordevice')),
            ],
        ),
    ]
