# Generated by Django 6.0.8 on 2026-10-02 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_set_existing_device_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'API client',
            },
        ),
        migrations.CreateModel(
            name='StatusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('soap', 'Soap'), ('toilet-paper', 'Toilet Paper'), ('tissue', 'Tissue Roll'), ('trash', 'Trash Bin'), ('ammonia', 'Amonia')], max_length=20)),
                ('condition', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('normal', 'Normal (green)'), ('warning', 'Warning (orange)'), ('critical', 'Critical (red)')], max_length=10)),
                ('min_level', models.FloatField(blank=True, help_text='Inclusive. Empty = no lower bound.', null=True)),
                ('max_level', models.FloatField(blank=True, help_text='Exclusive. Empty = no upper bound.', null=True)),
            ],
            options={
                'ordering': ('sensor_type', 'min_level'),
            },
        ),
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washroom.apiclient')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_responses', to='core.devicelist')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('battery', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(blank=True, choices=[('normal', 'Normal (green)'), ('warning', 'Warning (orange)'), ('critical', 'Critical (red)')], max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washroom.apiclient')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.devicelist')),
            ],
            options={
                'indexes': [models.Index(fields=['device', '-time'], name='washroom_se_device__0ae0e8_idx')],
            },
        ),
    ]
