# Generated by Django 6.0.8 on 2026-10-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devicelist_count_date'),
        ('washroom', '0002_seed_status_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordevice',
            name='type',
            field=models.CharField(choices=[('amonia', 'Amonia'), ('soap', 'Soap'), ('tissue', 'Tissue Roll'), ('toilet_paper', 'Toilet Paper'), ('trash', 'Trash Bin'), ('feedback', 'Customer Satisfaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusrule',
            name='sensor_type',
            field=models.CharField(choices=[('amonia', 'Amonia'), ('soap', 'Soap'), ('tissue', 'Tissue Roll'), ('toilet_paper', 'Toilet Paper'), ('trash', 'Trash Bin'), ('feedback', 'Customer Satisfaction')], max_length=20),
        ),
        migrations.CreateModel(
            name='Washroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(help_text='Label shown in the filter, e.g. "Lantai 2"', max_length=50)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita'), ('difabel', 'Difabel')], max_length=10)),
                ('people_counters', models.ManyToManyField(blank=True, related_name='washrooms', to='core.devicelist')),
            ],
            options={
                'ordering': ('building', 'floor', 'gender'),
            },
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='washroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='washroom.washroom'),
        ),
        migrations.AddConstraint(
            model_name='washroom',
            constraint=models.UniqueConstraint(fields=('building', 'floor', 'gender'), name='unique_washroom'),
        ),
    ]
