# Generated by Django 6.0.8 on 2026-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schedulerconfig_interval_seconds'),
        ('washroom', '0002_seed_status_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('device', 'external_id'), name='unique_reading_external_id_per_device'),
        ),
    ]
