# Generated by Django 6.0.8 on 2026-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_devicelist_numeric_pk'),
        ('washroom', '0003_reading_external_id_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='customerresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('device', 'external_id'), name='unique_response_external_id_per_device'),
        ),
    ]
