# Generated by Django 6.0.8 on 2026-10-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washroom', '0004_seed_washroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washroom.apiclient'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washroom.apiclient'),
        ),
    ]
