# Generated by Django 6.0.8 on 2026-10-01 04:21

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('current_count', models.IntegerField(default=0)),
                ('maximum_trigger', models.IntegerField(default=10)),
                ('baseline_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'device',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('token', 'ZK token'), ('event', 'ZK event'), ('notification', 'Work Order notification')], max_length=20)),
                ('url', models.URLField()),
                ('head', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'scheduler config',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('metadata_id', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField()),
                ('track_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('recognition_target', models.CharField(blank=True, max_length=100)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('counted', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devicelist')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('endpoint_url', models.CharField(max_length=500)),
                ('body', models.JSONField(blank=True, null=True)),
                ('head', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_status', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devicelist')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('response', models.JSONField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('endpoint_url', models.CharField(max_length=500)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.devicelist')),
            ],
        ),
    ]
