# Generated by Django 6.0.8 on 2026-10-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endpoint_is_active_real_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecap',
            fields=[
            ],
            options={
                'verbose_name': 'daily recap',
                'verbose_name_plural': 'daily recap',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.eventlog',),
        ),
    ]
