# Generated by Django 6.0.6 on 2026-10-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyrecap'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='count_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
