# Generated by Django 6.0.8 on 2026-10-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devicelist_count_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='building',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Pria'), ('female', 'Wanita')], max_length=10),
        ),
    ]
