# Generated by Django 6.0.8 on 2026-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_set_initial_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='type',
            field=models.CharField(choices=[('people', 'People Counting'), ('satisfaction', 'Customer Satisfaction'), ('soap', 'Soap'), ('toilet-paper', 'Toilet Paper'), ('tissue', 'Tissue Roll'), ('trash', 'Trash Bin'), ('ammonia', 'Amonia')], default='people', max_length=100),
        ),
    ]
