# Generated by Django 6.0.8 on 2026-10-05 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_set_existing_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerconfig',
            name='dashboard_refresh_seconds',
            field=models.PositiveIntegerField(default=60, help_text='How often open dashboard pages reload their data (10-3600 seconds).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
    ]
