# Generated by Django 6.0.8 on 2026-10-06 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schedulerconfig_interval_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['site__client__name', 'site__region__name', 'site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='core.area')),
            ],
            options={
                'ordering': ['area__site__client__name', 'area__site__region__name', 'area__site__name', 'area__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='devicelist',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.scope'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.client')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.region')),
            ],
            options={
                'ordering': ['client__name', 'region__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.site'),
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='unique_scope'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('client', 'region', 'name'), name='unique_site'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_area'),
        ),
    ]
