# Generated by Django 6.0.8 on 2026-10-06 08:00

from django.db import migrations, models


def _outcome(response_status, response):
    # Frozen copy of core.models.work_order_outcome as of this migration.
    http_ok = str(response_status).startswith("2")
    item = response[0] if isinstance(response, list) and response and isinstance(response[0], dict) else response
    if not isinstance(item, dict):
        return http_ok, ""  # no recognisable body: fall back to the HTTP status
    if "error" in item:
        results = item.get("results") or [{}]
        number = results[0].get("WO_NO") if isinstance(results[0], dict) else None
        return http_ok and item.get("error") in (0, "0"), str(number or "")
    return http_ok and item.get("status", "success") == "success", str(item.get("wo_id") or "")


def backfill(apps, schema_editor):
    NotificationLog = apps.get_model("core", "NotificationLog")
    for log in NotificationLog.objects.all():
        log.success, log.wo_number = _outcome(log.response_status, log.response)
        log.save(update_fields=["success", "wo_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_location_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='success',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='wo_number',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
