# Generated by Django 6.0.8 on 2026-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificationlog_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='success',
            field=models.BooleanField(db_default=False, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='wo_number',
            field=models.CharField(blank=True, db_default='', default='', editable=False, max_length=100),
        ),
    ]
