# Generated by Django 6.0.8 on 2026-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notificationlog_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
