"""Give DeviceList a numeric primary key and move the device's own ID to an editable `device_id`.

Before: `id` (varchar) was both the device ID sent by ZK / the sensor API and the primary key, so it
could not be edited without breaking every row that points at the device. After: `id` is an
auto-increment bigint and `device_id` (unique, editable) holds the device ID. All foreign keys,
including the washroom ones, are rewired to the new numeric id; existing rows keep their device.

PostgreSQL only (the project runs on PostgreSQL), hence raw SQL inside SeparateDatabaseAndState.
"""

from django.db import migrations, models

# (table, nullable, index name, extra SQL run after the FK column is rebuilt)
REFERENCING = [
    ("core_eventlog", False, "core_eventlog_device_id_idx", []),
    ("core_sensorlog", True, "core_sensorlog_device_id_idx", []),
    ("core_notificationlog", False, "core_notificationlog_device_id_idx", []),
    ("washroom_customerresponse", False, "washroom_customerresponse_device_id_idx", []),
    ("washroom_sensorreading", False, "washroom_sensorreading_device_id_idx", [
        # Re-create what the old varchar column carried (washroom/0003): Meta.indexes and the
        # partial unique constraint on (device, external_id).
        'CREATE INDEX washroom_se_device__0ae0e8_idx ON washroom_sensorreading (device_id, "time" DESC);',
        "CREATE UNIQUE INDEX unique_reading_external_id_per_device ON washroom_sensorreading "
        "(device_id, external_id) WHERE NOT (external_id = '');",
    ]),
]


def forward_sql():
    sql = [
        "ALTER TABLE core_devicelist ADD COLUMN device_id varchar(100);",
        "UPDATE core_devicelist SET device_id = id;",
        "ALTER TABLE core_devicelist ALTER COLUMN device_id SET NOT NULL;",
        # Existing rows get 1, 2, 3, ... from the identity sequence.
        "ALTER TABLE core_devicelist ADD COLUMN new_id bigint GENERATED BY DEFAULT AS IDENTITY;",
    ]
    for table, nullable, _, _ in REFERENCING:
        sql += [
            f"ALTER TABLE {table} ADD COLUMN device_new bigint;",
            f"UPDATE {table} t SET device_new = d.new_id FROM core_devicelist d WHERE d.id = t.device_id;",
            # Dropping the old varchar column also drops its FK constraint and indexes.
            f"ALTER TABLE {table} DROP COLUMN device_id;",
            f"ALTER TABLE {table} RENAME COLUMN device_new TO device_id;",
        ]
        if not nullable:
            sql.append(f"ALTER TABLE {table} ALTER COLUMN device_id SET NOT NULL;")
    sql += [
        "ALTER TABLE core_devicelist DROP COLUMN id;",
        "ALTER TABLE core_devicelist RENAME COLUMN new_id TO id;",
        "ALTER TABLE core_devicelist ADD CONSTRAINT core_devicelist_pkey PRIMARY KEY (id);",
        "ALTER TABLE core_devicelist ADD CONSTRAINT core_devicelist_device_id_key UNIQUE (device_id);",
        "CREATE INDEX core_devicelist_device_id_like ON core_devicelist (device_id varchar_pattern_ops);",
    ]
    for table, _, index, extra in REFERENCING:
        sql += [
            f"ALTER TABLE {table} ADD CONSTRAINT {table}_device_id_fk_core_devicelist_id FOREIGN KEY (device_id) "
            "REFERENCES core_devicelist (id) DEFERRABLE INITIALLY DEFERRED;",
            f"CREATE INDEX {index} ON {table} (device_id);",
            *extra,
        ]
    return sql


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_wo_completion"),
        # The washroom tables point at DeviceList too and must be rewired in the same step.
        ("washroom", "0003_reading_external_id_last_online"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(forward_sql())],
            state_operations=[
                migrations.AddField(
                    model_name="devicelist",
                    name="device_id",
                    field=models.CharField(
                        max_length=100, unique=True, default="",
                        help_text="The device's own ID (ZK deviceId / washroom API device_id). Editable; "
                                  "history stays linked because other tables point at the numeric id.",
                    ),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name="devicelist",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
