# Generated by Django 6.0.8 on 2026-10-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_wo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=50)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
