# Generated by Django 6.0.8 on 2026-10-09 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_devicelist_numeric_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('algospection', 'Algospection (Work Order)'), ('telegram', 'Telegram (Bot API)'), ('whatsapp', 'WhatsApp (Evolution API)'), ('email', 'Email (SMTP)'), ('webhook', 'Webhook')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret settings plus the NAMES of .env variables, never the secret itself. Telegram: {"token_env": "TELEGRAM_BOT_TOKEN"} (optional "base_url"). WhatsApp: {"base_url": "http://evolution:8080", "instance": "washroom"}. Algospection / Webhook / Email: usually empty.')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('GET', 'GET')], default='POST', help_text='HTTP method (webhook).', max_length=6)),
                ('head', models.JSONField(blank=True, default=dict, help_text='Default HTTP headers (JSON object). Placeholders {{…}}.')),
                ('body', models.JSONField(blank=True, default=dict, help_text='Default HTTP body (JSON object). Placeholders {{…}}.')),
                ('email_subject', models.CharField(blank=True, help_text='Email only. Placeholders {{…}}.', max_length=200)),
                ('email_body', models.TextField(blank=True, help_text='Email only. Placeholders {{…}}.')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Extra attempts after a failed send (Algospection: always 0).')),
                ('retry_delay_minutes', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, help_text='62812… (country code, no +).', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_priority', models.JSONField(blank=True, default=list, help_text='Order to try, e.g. ["whatsapp", "telegram", "email"]. Empty = that order.')),
                ('areas', models.ManyToManyField(blank=True, help_text='Supervisor of these areas.', related_name='recipients', to='core.area')),
                ('scopes', models.ManyToManyField(blank=True, help_text='Cleaner of these toilets.', related_name='recipients', to='core.scope')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(help_text='Telegram: chat_id · WhatsApp: number (62812…) or group JID (…@g.us) · Email: addresses · Webhook / Algospection: URL. Several numbers or addresses separated by commas.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.JSONField(blank=True, help_text="Empty = use the channel's headers.", null=True)),
                ('body', models.JSONField(blank=True, help_text="Empty = use the channel's body.", null=True)),
                ('email_subject', models.CharField(blank=True, help_text="Empty = use the channel's subject.", max_length=200)),
                ('email_body', models.TextField(blank=True, help_text="Empty = use the channel's email body.")),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchannels', to='automation.channel')),
            ],
            options={
                'ordering': ['channel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('people_threshold', 'Pengunjung mencapai batas'), ('sensor_status', 'Status sensor'), ('low_battery', 'Baterai lemah'), ('offline', 'Sensor offline / tidak ada data'), ('bad_rating', 'Rating buruk')], max_length=30)),
                ('severities', models.JSONField(blank=True, default=list, help_text='Status sensor: e.g. ["critical"] or ["critical", "warning"].')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Status sensor: status names, e.g. ["Habis", "Penuh"] (case-insensitive).')),
                ('battery_below', models.PositiveSmallIntegerField(blank=True, help_text='Baterai lemah: below this %.', null=True)),
                ('offline_minutes', models.PositiveIntegerField(default=60, help_text='Offline: no data for this many minutes.')),
                ('device_types', models.JSONField(blank=True, default=list, help_text='e.g. ["soap", "trash"]. Empty = every type.')),
                ('notify_on_duty', models.BooleanField(default=False, help_text='Also notify staff on duty: cleaners of the Scope and supervisors of the Area, together.')),
                ('contact_mode', models.CharField(choices=[('priority', 'Satu kontak sesuai prioritas petugas (pindah ke berikutnya kalau gagal)'), ('all', 'Semua kontak yang dimiliki petugas')], default='priority', max_length=10)),
                ('message_template', models.TextField(blank=True, help_text='Empty = the default text for the condition. Placeholders {{…}}.')),
                ('cooldown_minutes', models.PositiveIntegerField(default=0, help_text='0 = once per occurrence (until it returns to normal).')),
                ('areas', models.ManyToManyField(blank=True, related_name='automation_rules', to='core.area')),
                ('devices', models.ManyToManyField(blank=True, related_name='automation_rules', to='core.devicelist')),
                ('person_channels', models.ManyToManyField(blank=True, help_text='Channels used to reach staff (one Telegram, one WhatsApp, one Email channel).', related_name='person_rules', to='automation.channel')),
                ('scopes', models.ManyToManyField(blank=True, related_name='automation_rules', to='core.scope')),
                ('subchannels', models.ManyToManyField(blank=True, help_text='Groups / addresses always notified.', related_name='rules', to='automation.subchannel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel_type', models.CharField(blank=True, max_length=20)),
                ('tier', models.CharField(choices=[('subchannel', 'Subchannel'), ('cleaner', 'Cleaner (Scope)'), ('supervisor', 'Supervisor (Area)'), ('test', 'Pesan uji')], default='subchannel', max_length=12)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Berhasil'), ('failed', 'Gagal'), ('retry_scheduled', 'Retry dijadwalkan'), ('skipped', 'Dilewati')], max_length=20)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_status', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.devicelist')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.channel')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.recipient')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.rule')),
                ('subchannel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.subchannel')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='RuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_states', to='core.devicelist')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='automation.rule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'device'), name='unique_rule_device_state')],
            },
        ),
    ]
